# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=1.4.22
maven_group=us.potatoboy
archives_base_name=InvView
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.160.5+26.3
# trinkets_version=3.10.0 
# apoli_version=2.12.0
sgui_version=2.2.0+26.3
permission_api_version=0.7.0
