# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=1.4.22
maven_group=us.potatoboy
archives_base_name=InvView
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.152.1+26.2
trinkets_version=4.1.1+26.2
# apoli_version=2.12.0
sgui_version=2.1.0+26.2
permission_api_version=0.7.0
